// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file macaroon/v1/query.proto (package macaroon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QueryRefreshTokenRequest, QueryRefreshTokenResponse, QueryValidateTokenRequest, QueryValidateTokenResponse } from "./query_pb.js";

const TYPE_NAME = "macaroon.v1.Query";

/**
 * Params queries all parameters of the module.
 *
 * @generated from rpc macaroon.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * RefreshToken refreshes a macaroon token as post authentication.
 *
 * @generated from rpc macaroon.v1.Query.RefreshToken
 */
export const QueryRefreshTokenService = {
  typeName: TYPE_NAME,
  method: "RefreshToken",
  Request: QueryRefreshTokenRequest,
  Response: QueryRefreshTokenResponse,
} as const;

/**
 * ValidateToken validates a macaroon token as pre authentication.
 *
 * @generated from rpc macaroon.v1.Query.ValidateToken
 */
export const QueryValidateTokenService = {
  typeName: TYPE_NAME,
  method: "ValidateToken",
  Request: QueryValidateTokenRequest,
  Response: QueryValidateTokenResponse,
} as const;

