// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file did/v1/tx.proto (package did.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgExecuteTx, MsgExecuteTxResponse, MsgRegisterController, MsgRegisterControllerResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "did.v1.Msg";

/**
 * ExecuteTx executes a transaction on the Sonr Blockchain. It leverages
 * Macaroon for verification.
 *
 * @generated from rpc did.v1.Msg.ExecuteTx
 */
export const MsgExecuteTxService = {
  typeName: TYPE_NAME,
  method: "ExecuteTx",
  Request: MsgExecuteTx,
  Response: MsgExecuteTxResponse,
} as const;

/**
 * RegisterController initializes a controller with the given authentication
 * set, address, cid, publicKey, and user-defined alias.
 *
 * @generated from rpc did.v1.Msg.RegisterController
 */
export const MsgRegisterControllerService = {
  typeName: TYPE_NAME,
  method: "RegisterController",
  Request: MsgRegisterController,
  Response: MsgRegisterControllerResponse,
} as const;

/**
 * UpdateParams defines a governance operation for updating the parameters.
 *
 * @generated from rpc did.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

