// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file service/v1/query.proto (package service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "service.v1.Query";

/**
 * Params queries all parameters of the module.
 *
 * @generated from rpc service.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

