// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file service/v1/state.proto (package service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message service.v1.Metadata
 */
export class Metadata extends Message<Metadata> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string origin = 2;
   */
  origin = "";

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * @generated from field: string category = 5;
   */
  category = "";

  /**
   * @generated from field: service.v1.URI icon = 6;
   */
  icon?: URI;

  /**
   * @generated from field: repeated string tags = 7;
   */
  tags: string[] = [];

  constructor(data?: PartialMessage<Metadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "service.v1.Metadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "icon", kind: "message", T: URI },
    { no: 7, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Metadata {
    return new Metadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Metadata {
    return new Metadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Metadata {
    return new Metadata().fromJsonString(jsonString, options);
  }

  static equals(a: Metadata | PlainMessage<Metadata> | undefined, b: Metadata | PlainMessage<Metadata> | undefined): boolean {
    return proto3.util.equals(Metadata, a, b);
  }
}

/**
 * Profile represents a DID alias
 *
 * @generated from message service.v1.Profile
 */
export class Profile extends Message<Profile> {
  /**
   * The unique identifier of the alias
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * The alias of the DID
   *
   * @generated from field: string subject = 2;
   */
  subject = "";

  /**
   * Origin of the alias
   *
   * @generated from field: string origin = 3;
   */
  origin = "";

  /**
   * Controller of the alias
   *
   * @generated from field: string controller = 4;
   */
  controller = "";

  constructor(data?: PartialMessage<Profile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "service.v1.Profile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "controller", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Profile {
    return new Profile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Profile {
    return new Profile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Profile {
    return new Profile().fromJsonString(jsonString, options);
  }

  static equals(a: Profile | PlainMessage<Profile> | undefined, b: Profile | PlainMessage<Profile> | undefined): boolean {
    return proto3.util.equals(Profile, a, b);
  }
}

/**
 * @generated from message service.v1.URI
 */
export class URI extends Message<URI> {
  /**
   * @generated from field: service.v1.URI.Protocol protocol = 1;
   */
  protocol = URI_Protocol.HTTPS;

  /**
   * @generated from field: string uri = 2;
   */
  uri = "";

  constructor(data?: PartialMessage<URI>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "service.v1.URI";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "protocol", kind: "enum", T: proto3.getEnumType(URI_Protocol) },
    { no: 2, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): URI {
    return new URI().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): URI {
    return new URI().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): URI {
    return new URI().fromJsonString(jsonString, options);
  }

  static equals(a: URI | PlainMessage<URI> | undefined, b: URI | PlainMessage<URI> | undefined): boolean {
    return proto3.util.equals(URI, a, b);
  }
}

/**
 * @generated from enum service.v1.URI.Protocol
 */
export enum URI_Protocol {
  /**
   * @generated from enum value: HTTPS = 0;
   */
  HTTPS = 0,

  /**
   * @generated from enum value: IPFS = 1;
   */
  IPFS = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(URI_Protocol)
proto3.util.setEnumType(URI_Protocol, "service.v1.URI.Protocol", [
  { no: 0, name: "HTTPS" },
  { no: 1, name: "IPFS" },
]);

