// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vault/v1/query.proto (package vault.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BuildTxRequest, BuildTxResponse, QueryParamsRequest, QueryParamsResponse, SyncRequest, SyncResponse } from "./query_pb.js";

const TYPE_NAME = "vault.v1.Query";

/**
 * Params queries all parameters of the module.
 *
 * @generated from rpc vault.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * BuildTx builds an unsigned transaction message for the given PKL.
 *
 * @generated from rpc vault.v1.Query.BuildTx
 */
export const QueryBuildTxService = {
  typeName: TYPE_NAME,
  method: "BuildTx",
  Request: BuildTxRequest,
  Response: BuildTxResponse,
} as const;

/**
 * Sync queries the DID document by its id. And returns the required PKL
 * information
 *
 * @generated from rpc vault.v1.Query.Sync
 */
export const QuerySyncService = {
  typeName: TYPE_NAME,
  method: "Sync",
  Request: SyncRequest,
  Response: SyncResponse,
} as const;

