// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vault/v1/tx.proto (package vault.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAllocateVault, MsgAllocateVaultResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "vault.v1.Msg";

/**
 * AllocateVault assembles a sqlite3 database in a local directory and returns
 * the CID of the database. this operation is called by services initiating a
 * controller registration.
 *
 * @generated from rpc vault.v1.Msg.AllocateVault
 */
export const MsgAllocateVaultService = {
  typeName: TYPE_NAME,
  method: "AllocateVault",
  Request: MsgAllocateVault,
  Response: MsgAllocateVaultResponse,
} as const;

/**
 * UpdateParams defines a governance operation for updating the parameters.
 *
 * Since: cosmos-sdk 0.47
 *
 * @generated from rpc vault.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

